export const TYPE_COLORS: Record<string, string> = {
  Normal: 'var(--color-type-normal)',
  Fire: 'var(--color-type-fire)',
  Water: 'var(--color-type-water)',
  Grass: 'var(--color-type-grass)',
  Electric: 'var(--color-type-electric)',
  Ice: 'var(--color-type-ice)',
  Fighting: 'var(--color-type-fighting)',
  Poison: 'var(--color-type-poison)',
  Ground: 'var(--color-type-ground)',
  Flying: 'var(--color-type-flying)',
  Psychic: 'var(--color-type-psychic)',
  Bug: 'var(--color-type-bug)',
  Rock: 'var(--color-type-rock)',
  Ghost: 'var(--color-type-ghost)',
  Dragon: 'var(--color-type-dragon)',
  Dark: 'var(--color-type-dark)',
  Steel: 'var(--color-type-steel)',
  Fairy: 'var(--color-type-fairy)',
  Stellar: 'var(--color-type-stellar)',
};
